### ISSUE TITLE
关于图片路径错误的问题

### ISSUE THREAD

**Issue by DophinL** [JeremyWei/baidu-ocr#2]
我输入一个错误的图片路径,ocr.scan不会抛错，导致我花了挺多时间去找问题在哪。

问题好像出在fs.createReadStream( image )
我做了个测试
```javascript
//baidu-ocr
app.get('/ocr', function(req, res) {
    var falsePath = 'false path';
    var ocr = require('baidu-ocr').create('afabe534103b88dec8ae8cd33c2ef4f0');
    ocr.scan('LocateRecognize', 'CHN_ENG', 2, falsePath, function(err, data) {

    });  //不抛错
})

//测试fs
app.get('/fs', function(req, res) {
    var fs = require('fs');
    var falsePath = 'false path';
    fs.createReadStream(falsePath);  //抛错
})
```

麻烦看一下，感谢！

**Comment by Birjemin** [comment]
用php调用 识别效果很差，求解
<?php
//header("Content-type:text/html;charset=utf-8");
$filename = "1.jpg";
$fp = fopen($filename, "rb");
$content = fread($fp, filesize($filename));
$f_bs = base64_encode($content);
//echo $f_bs;
fclose($fp);
//die();
$ch = curl_init();
$url = 'http://apis.baidu.com/apistore/idlocr/ocr';
$header = array(
    'Content-Type:application/x-www-form-urlencoded',
    'apikey: 5aefdbc372d4a9d0bc48e954c319715e',
);
$data = "fromdevice=pc&clientip=169.254.247.238&detecttype=Recognize&languagetype=CHN_ENG&imagetype=1&image=".$f_bs;
// 添加apikey到header
curl_setopt($ch, CURLOPT_HTTPHEADER  , $header);
// 添加参数
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// 执行HTTP请求
curl_setopt($ch , CURLOPT_URL , $url);
$res = curl_exec($ch);
var_dump(json_decode($res));
?>

**Comment by JeremyWei** [comment]
@Birjemin 这个API是由百度提供的

**Comment by Birjemin** [comment]
已采用google的tesseract，模型够大的话，效果杠杠的,thanks
